#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Prepare a folder-based review package for cluster inspection and manual labeling.

Reads cluster assignments and writes:
- review/cluster_XXXX/questions.csv for each cluster
- review/unclustered/questions.csv for noise/unassigned
- review/cluster_overview.csv (size + confidence summaries)
- review/labels_template.csv (one row per cluster to fill in labels)

This is designed for the outputs generated by bottom_up_clustering.py.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd

DEFAULT_OUTPUT_DIR = r"C:\Users\TorsteinDeBesche\NIFU\21571 Folkehelse og livsmestring - General\Ap2c Informasjonskanal for unge\Positron_project\outputs"
DEFAULT_ASSIGNMENTS = "A_cluster_assignments.parquet"
DEFAULT_REVIEW_DIR = "cluster_review"


def sanitize_columns(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    required = {
        "cluster_id": -1,
        "body_norm": "",
        "cluster_sim": 0.0,
        "cluster_margin": 0.0,
    }
    for col, default in required.items():
        if col not in out.columns:
            out[col] = default
    out["cluster_id"] = pd.to_numeric(out["cluster_id"], errors="coerce").fillna(-1).astype(int)
    out["cluster_sim"] = pd.to_numeric(out["cluster_sim"], errors="coerce").fillna(0.0)
    out["cluster_margin"] = pd.to_numeric(out["cluster_margin"], errors="coerce").fillna(0.0)
    out["body_norm"] = out["body_norm"].astype(str)
    return out


def cluster_folder_name(cluster_id: int) -> str:
    return f"cluster_{cluster_id:04d}"


def write_cluster_files(df: pd.DataFrame, review_dir: Path, sample_per_cluster: int) -> pd.DataFrame:
    clustered = df[df["cluster_id"] >= 0].copy()
    overview_rows = []

    for cid, grp in clustered.groupby("cluster_id"):
        cdir = review_dir / cluster_folder_name(int(cid))
        cdir.mkdir(parents=True, exist_ok=True)

        grp_sorted = grp.sort_values(["cluster_sim", "cluster_margin"], ascending=[False, False])
        grp_sorted.to_csv(cdir / "questions.csv", index=False, encoding="utf-8")

        sample = grp_sorted.head(sample_per_cluster)
        sample[["body_norm", "cluster_sim", "cluster_margin"]].to_csv(
            cdir / "sample_for_labeling.csv", index=False, encoding="utf-8"
        )

        overview_rows.append(
            {
                "cluster_id": int(cid),
                "folder": cdir.name,
                "size": int(len(grp_sorted)),
                "sim_mean": float(grp_sorted["cluster_sim"].mean()),
                "sim_p10": float(grp_sorted["cluster_sim"].quantile(0.10)),
                "margin_mean": float(grp_sorted["cluster_margin"].mean()),
            }
        )

    return pd.DataFrame(overview_rows).sort_values("size", ascending=False)


def write_unclustered(df: pd.DataFrame, review_dir: Path, sample_unclustered: int) -> int:
    unclustered = df[df["cluster_id"] < 0].copy()
    udir = review_dir / "unclustered"
    udir.mkdir(parents=True, exist_ok=True)

    unclustered_sorted = unclustered.sort_values(["cluster_sim", "cluster_margin"], ascending=[False, True])
    unclustered_sorted.to_csv(udir / "questions.csv", index=False, encoding="utf-8")
    unclustered_sorted.head(sample_unclustered).to_csv(
        udir / "sample_for_review.csv", index=False, encoding="utf-8"
    )
    return int(len(unclustered_sorted))


def write_labels_template(overview: pd.DataFrame, review_dir: Path) -> None:
    labels = overview[["cluster_id", "folder", "size"]].copy()
    labels["label_name"] = ""
    labels["label_description"] = ""
    labels["merge_into_cluster_id"] = ""
    labels["drop_cluster"] = ""
    labels.to_csv(review_dir / "labels_template.csv", index=False, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Create folder-based files for cluster review and labeling.")
    parser.add_argument("--output-dir", default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--assignments", default=DEFAULT_ASSIGNMENTS, help="Parquet file inside output-dir")
    parser.add_argument("--review-dir", default=DEFAULT_REVIEW_DIR, help="Folder (inside output-dir) for review package")
    parser.add_argument("--sample-per-cluster", type=int, default=50)
    parser.add_argument("--sample-unclustered", type=int, default=500)
    args = parser.parse_args()

    outdir = Path(args.output_dir)
    assign_path = outdir / args.assignments
    review_dir = outdir / args.review_dir
    review_dir.mkdir(parents=True, exist_ok=True)

    if not assign_path.exists():
        raise FileNotFoundError(f"Assignments file not found: {assign_path}")

    df = pd.read_parquet(assign_path)
    df = sanitize_columns(df)

    overview = write_cluster_files(df, review_dir, sample_per_cluster=args.sample_per_cluster)
    overview.to_csv(review_dir / "cluster_overview.csv", index=False, encoding="utf-8")

    n_unclustered = write_unclustered(df, review_dir, sample_unclustered=args.sample_unclustered)
    write_labels_template(overview, review_dir)

    manifest = {
        "assignments": str(assign_path),
        "review_dir": str(review_dir),
        "n_rows": int(len(df)),
        "n_clusters": int(len(overview)),
        "n_unclustered": int(n_unclustered),
        "sample_per_cluster": int(args.sample_per_cluster),
        "sample_unclustered": int(args.sample_unclustered),
    }
    with open(review_dir / "review_manifest.json", "w", encoding="utf-8") as f:
        json.dump(manifest, f, ensure_ascii=False, indent=2)

    print(json.dumps(manifest, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
